
// This is ammo.js, a port of Bullet Physics to JavaScript. zlib licensed.

var Ammo = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Ammo) {
  Ammo = Ammo || {};


var a;a||(a=typeof Ammo !== 'undefined' ? Ammo : {});var aa;a.ready=new Promise(function(b){aa=b});var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=a[f]);var h=!1,k=!1,ba=!1,ca=!1;h="object"===typeof window;k="function"===typeof importScripts;ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!h&&!ba&&!k;var l="",n,p,da,ea;
if(ba)l=k?require("path").dirname(l)+"/":__dirname+"/",n=function(b,c){da||(da=require("fs"));ea||(ea=require("path"));b=ea.normalize(b);return da.readFileSync(b,c?null:"utf8")},p=function(b){b=n(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",q),a.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=
typeof read&&(n=function(b){return read(b)}),p=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"===typeof b);return b},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(h||k)k?l=self.location.href:document.currentScript&&(l=document.currentScript.src),_scriptDir&&(l=_scriptDir),l=0!==l.indexOf("blob:")?l.substr(0,
l.lastIndexOf("/")+1):"",n=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},k&&(p=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var fa=a.print||console.log.bind(console),r=a.printErr||console.warn.bind(console);for(f in d)d.hasOwnProperty(f)&&(a[f]=d[f]);d=null;var t;a.wasmBinary&&(t=a.wasmBinary);var noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);
"object"!==typeof WebAssembly&&r("no native wasm support detected");var ha,ia=new WebAssembly.Table({initial:535,maximum:535,element:"anyfunc"}),ja=!1;function assert(b,c){b||q("Assertion failed: "+c)}var ka,la,u,ma,na=a.INITIAL_MEMORY||16777216;if(ha=a.wasmMemory?a.wasmMemory:new WebAssembly.Memory({initial:na/65536,maximum:na/65536}))ka=ha.buffer;na=ka.byteLength;var v=ka;ka=v;a.HEAP8=new Int8Array(v);a.HEAP16=new Int16Array(v);a.HEAP32=u=new Int32Array(v);a.HEAPU8=la=new Uint8Array(v);
a.HEAPU16=new Uint16Array(v);a.HEAPU32=new Uint32Array(v);a.HEAPF32=ma=new Float32Array(v);a.HEAPF64=new Float64Array(v);u[4908]=5262672;function oa(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var e=c.fc;"number"===typeof e?void 0===c.cc?a.dynCall_v(e):a.dynCall_vi(e,c.cc):e(void 0===c.cc?null:c.cc)}}}var pa=[],qa=[],ra=[],sa=[];function ta(){var b=a.preRun.shift();pa.unshift(b)}var w=0,ua=null,x=null;a.preloadedImages={};a.preloadedAudios={};
function q(b){if(a.onAbort)a.onAbort(b);b+="";fa(b);r(b);ja=!0;throw new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function va(b){var c=y;return String.prototype.startsWith?c.startsWith(b):0===c.indexOf(b)}function wa(){return va("data:application/octet-stream;base64,")}var y="ammo.wasm.wasm";if(!wa()){var xa=y;y=a.locateFile?a.locateFile(xa,l):l+xa}
function ya(){try{if(t)return new Uint8Array(t);if(p)return p(y);throw"both async and sync fetching of the wasm failed";}catch(b){q(b)}}function za(){return t||!h&&!k||"function"!==typeof fetch||va("file://")?new Promise(function(b){b(ya())}):fetch(y,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+y+"'";return b.arrayBuffer()}).catch(function(){return ya()})}qa.push({fc:function(){Aa()}});
var Ba={d:function(){q()},b:function(b,c,e){la.copyWithin(b,c,c+e)},c:function(){q("OOM")},a:function(b){var c=Date.now();u[b>>2]=c/1E3|0;u[b+4>>2]=c%1E3*1E3|0;return 0},memory:ha,table:ia};
(function(){function b(m){a.asm=m.exports;w--;a.monitorRunDependencies&&a.monitorRunDependencies(w);0==w&&(null!==ua&&(clearInterval(ua),ua=null),x&&(m=x,x=null,m()))}function c(m){b(m.instance)}function e(m){return za().then(function(L){return WebAssembly.instantiate(L,g)}).then(m,function(L){r("failed to asynchronously prepare wasm: "+L);q(L)})}var g={a:Ba};w++;a.monitorRunDependencies&&a.monitorRunDependencies(w);if(a.instantiateWasm)try{return a.instantiateWasm(g,b)}catch(m){return r("Module.instantiateWasm callback failed with error: "+
m),!1}(function(){if(t||"function"!==typeof WebAssembly.instantiateStreaming||wa()||va("file://")||"function"!==typeof fetch)return e(c);fetch(y,{credentials:"same-origin"}).then(function(m){return WebAssembly.instantiateStreaming(m,g).then(c,function(L){r("wasm streaming compile failed: "+L);r("falling back to ArrayBuffer instantiation");return e(c)})})})();return{}})();var Aa=a.___wasm_call_ctors=function(){return(Aa=a.___wasm_call_ctors=a.asm.e).apply(null,arguments)};
a.___em_js__array_bounds_check_error=function(){return(a.___em_js__array_bounds_check_error=a.asm.f).apply(null,arguments)};
var Ca=a._emscripten_bind_btCollisionObject_setActivationState_1=function(){return(Ca=a._emscripten_bind_btCollisionObject_setActivationState_1=a.asm.g).apply(null,arguments)},Da=a._emscripten_bind_btCollisionObject___destroy___0=function(){return(Da=a._emscripten_bind_btCollisionObject___destroy___0=a.asm.h).apply(null,arguments)},Ea=a._emscripten_bind_btDispatcher___destroy___0=function(){return(Ea=a._emscripten_bind_btDispatcher___destroy___0=a.asm.i).apply(null,arguments)},Fa=a._emscripten_bind_btCollisionConfiguration___destroy___0=
function(){return(Fa=a._emscripten_bind_btCollisionConfiguration___destroy___0=a.asm.j).apply(null,arguments)},Ga=a._emscripten_bind_btSoftBodySolver___destroy___0=function(){return(Ga=a._emscripten_bind_btSoftBodySolver___destroy___0=a.asm.k).apply(null,arguments)},Ha=a._emscripten_bind_btBroadphaseInterface___destroy___0=function(){return(Ha=a._emscripten_bind_btBroadphaseInterface___destroy___0=a.asm.l).apply(null,arguments)},Ia=a._emscripten_bind_btConstraintSolver___destroy___0=function(){return(Ia=
a._emscripten_bind_btConstraintSolver___destroy___0=a.asm.m).apply(null,arguments)},Ja=a._emscripten_bind_btDbvtBroadphase_btDbvtBroadphase_0=function(){return(Ja=a._emscripten_bind_btDbvtBroadphase_btDbvtBroadphase_0=a.asm.n).apply(null,arguments)},Ka=a._emscripten_bind_btDbvtBroadphase___destroy___0=function(){return(Ka=a._emscripten_bind_btDbvtBroadphase___destroy___0=a.asm.o).apply(null,arguments)},La=a._emscripten_bind_btDefaultSoftBodySolver_btDefaultSoftBodySolver_0=function(){return(La=a._emscripten_bind_btDefaultSoftBodySolver_btDefaultSoftBodySolver_0=
a.asm.p).apply(null,arguments)},Ma=a._emscripten_bind_btDefaultSoftBodySolver___destroy___0=function(){return(Ma=a._emscripten_bind_btDefaultSoftBodySolver___destroy___0=a.asm.q).apply(null,arguments)},Na=a._emscripten_bind_btCollisionDispatcher_btCollisionDispatcher_1=function(){return(Na=a._emscripten_bind_btCollisionDispatcher_btCollisionDispatcher_1=a.asm.r).apply(null,arguments)},Oa=a._emscripten_bind_btCollisionDispatcher___destroy___0=function(){return(Oa=a._emscripten_bind_btCollisionDispatcher___destroy___0=
a.asm.s).apply(null,arguments)},Pa=a._emscripten_bind_btSequentialImpulseConstraintSolver_btSequentialImpulseConstraintSolver_0=function(){return(Pa=a._emscripten_bind_btSequentialImpulseConstraintSolver_btSequentialImpulseConstraintSolver_0=a.asm.t).apply(null,arguments)},Qa=a._emscripten_bind_btSequentialImpulseConstraintSolver___destroy___0=function(){return(Qa=a._emscripten_bind_btSequentialImpulseConstraintSolver___destroy___0=a.asm.u).apply(null,arguments)},Ra=a._emscripten_bind_VoidPtr___destroy___0=
function(){return(Ra=a._emscripten_bind_VoidPtr___destroy___0=a.asm.v).apply(null,arguments)},Sa=a._emscripten_bind_Config_get_kVCF_0=function(){return(Sa=a._emscripten_bind_Config_get_kVCF_0=a.asm.w).apply(null,arguments)},Ta=a._emscripten_bind_Config_set_kVCF_1=function(){return(Ta=a._emscripten_bind_Config_set_kVCF_1=a.asm.x).apply(null,arguments)},Ua=a._emscripten_bind_Config_get_kDP_0=function(){return(Ua=a._emscripten_bind_Config_get_kDP_0=a.asm.y).apply(null,arguments)},Va=a._emscripten_bind_Config_set_kDP_1=
function(){return(Va=a._emscripten_bind_Config_set_kDP_1=a.asm.z).apply(null,arguments)},Wa=a._emscripten_bind_Config_get_kDG_0=function(){return(Wa=a._emscripten_bind_Config_get_kDG_0=a.asm.A).apply(null,arguments)},Xa=a._emscripten_bind_Config_set_kDG_1=function(){return(Xa=a._emscripten_bind_Config_set_kDG_1=a.asm.B).apply(null,arguments)},Ya=a._emscripten_bind_Config_get_kLF_0=function(){return(Ya=a._emscripten_bind_Config_get_kLF_0=a.asm.C).apply(null,arguments)},Za=a._emscripten_bind_Config_set_kLF_1=
function(){return(Za=a._emscripten_bind_Config_set_kLF_1=a.asm.D).apply(null,arguments)},$a=a._emscripten_bind_Config_get_kPR_0=function(){return($a=a._emscripten_bind_Config_get_kPR_0=a.asm.E).apply(null,arguments)},ab=a._emscripten_bind_Config_set_kPR_1=function(){return(ab=a._emscripten_bind_Config_set_kPR_1=a.asm.F).apply(null,arguments)},bb=a._emscripten_bind_Config_get_kVC_0=function(){return(bb=a._emscripten_bind_Config_get_kVC_0=a.asm.G).apply(null,arguments)},cb=a._emscripten_bind_Config_set_kVC_1=
function(){return(cb=a._emscripten_bind_Config_set_kVC_1=a.asm.H).apply(null,arguments)},db=a._emscripten_bind_Config_get_kDF_0=function(){return(db=a._emscripten_bind_Config_get_kDF_0=a.asm.I).apply(null,arguments)},eb=a._emscripten_bind_Config_set_kDF_1=function(){return(eb=a._emscripten_bind_Config_set_kDF_1=a.asm.J).apply(null,arguments)},fb=a._emscripten_bind_Config_get_kMT_0=function(){return(fb=a._emscripten_bind_Config_get_kMT_0=a.asm.K).apply(null,arguments)},gb=a._emscripten_bind_Config_set_kMT_1=
function(){return(gb=a._emscripten_bind_Config_set_kMT_1=a.asm.L).apply(null,arguments)},hb=a._emscripten_bind_Config_get_kCHR_0=function(){return(hb=a._emscripten_bind_Config_get_kCHR_0=a.asm.M).apply(null,arguments)},ib=a._emscripten_bind_Config_set_kCHR_1=function(){return(ib=a._emscripten_bind_Config_set_kCHR_1=a.asm.N).apply(null,arguments)},jb=a._emscripten_bind_Config_get_kKHR_0=function(){return(jb=a._emscripten_bind_Config_get_kKHR_0=a.asm.O).apply(null,arguments)},kb=a._emscripten_bind_Config_set_kKHR_1=
function(){return(kb=a._emscripten_bind_Config_set_kKHR_1=a.asm.P).apply(null,arguments)},lb=a._emscripten_bind_Config_get_kSHR_0=function(){return(lb=a._emscripten_bind_Config_get_kSHR_0=a.asm.Q).apply(null,arguments)},mb=a._emscripten_bind_Config_set_kSHR_1=function(){return(mb=a._emscripten_bind_Config_set_kSHR_1=a.asm.R).apply(null,arguments)},nb=a._emscripten_bind_Config_get_kAHR_0=function(){return(nb=a._emscripten_bind_Config_get_kAHR_0=a.asm.S).apply(null,arguments)},ob=a._emscripten_bind_Config_set_kAHR_1=
function(){return(ob=a._emscripten_bind_Config_set_kAHR_1=a.asm.T).apply(null,arguments)},pb=a._emscripten_bind_Config_get_kSRHR_CL_0=function(){return(pb=a._emscripten_bind_Config_get_kSRHR_CL_0=a.asm.U).apply(null,arguments)},qb=a._emscripten_bind_Config_set_kSRHR_CL_1=function(){return(qb=a._emscripten_bind_Config_set_kSRHR_CL_1=a.asm.V).apply(null,arguments)},rb=a._emscripten_bind_Config_get_kSKHR_CL_0=function(){return(rb=a._emscripten_bind_Config_get_kSKHR_CL_0=a.asm.W).apply(null,arguments)},
sb=a._emscripten_bind_Config_set_kSKHR_CL_1=function(){return(sb=a._emscripten_bind_Config_set_kSKHR_CL_1=a.asm.X).apply(null,arguments)},tb=a._emscripten_bind_Config_get_kSSHR_CL_0=function(){return(tb=a._emscripten_bind_Config_get_kSSHR_CL_0=a.asm.Y).apply(null,arguments)},ub=a._emscripten_bind_Config_set_kSSHR_CL_1=function(){return(ub=a._emscripten_bind_Config_set_kSSHR_CL_1=a.asm.Z).apply(null,arguments)},vb=a._emscripten_bind_Config_get_kSR_SPLT_CL_0=function(){return(vb=a._emscripten_bind_Config_get_kSR_SPLT_CL_0=
a.asm._).apply(null,arguments)},wb=a._emscripten_bind_Config_set_kSR_SPLT_CL_1=function(){return(wb=a._emscripten_bind_Config_set_kSR_SPLT_CL_1=a.asm.$).apply(null,arguments)},xb=a._emscripten_bind_Config_get_kSK_SPLT_CL_0=function(){return(xb=a._emscripten_bind_Config_get_kSK_SPLT_CL_0=a.asm.aa).apply(null,arguments)},yb=a._emscripten_bind_Config_set_kSK_SPLT_CL_1=function(){return(yb=a._emscripten_bind_Config_set_kSK_SPLT_CL_1=a.asm.ba).apply(null,arguments)},zb=a._emscripten_bind_Config_get_kSS_SPLT_CL_0=
function(){return(zb=a._emscripten_bind_Config_get_kSS_SPLT_CL_0=a.asm.ca).apply(null,arguments)},Ab=a._emscripten_bind_Config_set_kSS_SPLT_CL_1=function(){return(Ab=a._emscripten_bind_Config_set_kSS_SPLT_CL_1=a.asm.da).apply(null,arguments)},Bb=a._emscripten_bind_Config_get_maxvolume_0=function(){return(Bb=a._emscripten_bind_Config_get_maxvolume_0=a.asm.ea).apply(null,arguments)},Cb=a._emscripten_bind_Config_set_maxvolume_1=function(){return(Cb=a._emscripten_bind_Config_set_maxvolume_1=a.asm.fa).apply(null,
arguments)},Db=a._emscripten_bind_Config_get_timescale_0=function(){return(Db=a._emscripten_bind_Config_get_timescale_0=a.asm.ga).apply(null,arguments)},Eb=a._emscripten_bind_Config_set_timescale_1=function(){return(Eb=a._emscripten_bind_Config_set_timescale_1=a.asm.ha).apply(null,arguments)},Fb=a._emscripten_bind_Config_get_viterations_0=function(){return(Fb=a._emscripten_bind_Config_get_viterations_0=a.asm.ia).apply(null,arguments)},Gb=a._emscripten_bind_Config_set_viterations_1=function(){return(Gb=
a._emscripten_bind_Config_set_viterations_1=a.asm.ja).apply(null,arguments)},Hb=a._emscripten_bind_Config_get_piterations_0=function(){return(Hb=a._emscripten_bind_Config_get_piterations_0=a.asm.ka).apply(null,arguments)},Ib=a._emscripten_bind_Config_set_piterations_1=function(){return(Ib=a._emscripten_bind_Config_set_piterations_1=a.asm.la).apply(null,arguments)},Jb=a._emscripten_bind_Config_get_diterations_0=function(){return(Jb=a._emscripten_bind_Config_get_diterations_0=a.asm.ma).apply(null,arguments)},
Kb=a._emscripten_bind_Config_set_diterations_1=function(){return(Kb=a._emscripten_bind_Config_set_diterations_1=a.asm.na).apply(null,arguments)},Lb=a._emscripten_bind_Config_get_citerations_0=function(){return(Lb=a._emscripten_bind_Config_get_citerations_0=a.asm.oa).apply(null,arguments)},Mb=a._emscripten_bind_Config_set_citerations_1=function(){return(Mb=a._emscripten_bind_Config_set_citerations_1=a.asm.pa).apply(null,arguments)},Nb=a._emscripten_bind_Config_get_collisions_0=function(){return(Nb=
a._emscripten_bind_Config_get_collisions_0=a.asm.qa).apply(null,arguments)},Ob=a._emscripten_bind_Config_set_collisions_1=function(){return(Ob=a._emscripten_bind_Config_set_collisions_1=a.asm.ra).apply(null,arguments)},Pb=a._emscripten_bind_Config___destroy___0=function(){return(Pb=a._emscripten_bind_Config___destroy___0=a.asm.sa).apply(null,arguments)},Qb=a._emscripten_bind_Node_get_m_x_0=function(){return(Qb=a._emscripten_bind_Node_get_m_x_0=a.asm.ta).apply(null,arguments)},Rb=a._emscripten_bind_Node_set_m_x_1=
function(){return(Rb=a._emscripten_bind_Node_set_m_x_1=a.asm.ua).apply(null,arguments)},Sb=a._emscripten_bind_Node_get_m_q_0=function(){return(Sb=a._emscripten_bind_Node_get_m_q_0=a.asm.va).apply(null,arguments)},Tb=a._emscripten_bind_Node_set_m_q_1=function(){return(Tb=a._emscripten_bind_Node_set_m_q_1=a.asm.wa).apply(null,arguments)},Ub=a._emscripten_bind_Node_get_m_v_0=function(){return(Ub=a._emscripten_bind_Node_get_m_v_0=a.asm.xa).apply(null,arguments)},Vb=a._emscripten_bind_Node_set_m_v_1=function(){return(Vb=
a._emscripten_bind_Node_set_m_v_1=a.asm.ya).apply(null,arguments)},Wb=a._emscripten_bind_Node_get_m_f_0=function(){return(Wb=a._emscripten_bind_Node_get_m_f_0=a.asm.za).apply(null,arguments)},Xb=a._emscripten_bind_Node_set_m_f_1=function(){return(Xb=a._emscripten_bind_Node_set_m_f_1=a.asm.Aa).apply(null,arguments)},Yb=a._emscripten_bind_Node_get_m_n_0=function(){return(Yb=a._emscripten_bind_Node_get_m_n_0=a.asm.Ba).apply(null,arguments)},Zb=a._emscripten_bind_Node_set_m_n_1=function(){return(Zb=a._emscripten_bind_Node_set_m_n_1=
a.asm.Ca).apply(null,arguments)},$b=a._emscripten_bind_Node_get_m_im_0=function(){return($b=a._emscripten_bind_Node_get_m_im_0=a.asm.Da).apply(null,arguments)},ac=a._emscripten_bind_Node_set_m_im_1=function(){return(ac=a._emscripten_bind_Node_set_m_im_1=a.asm.Ea).apply(null,arguments)},bc=a._emscripten_bind_Node_get_m_area_0=function(){return(bc=a._emscripten_bind_Node_get_m_area_0=a.asm.Fa).apply(null,arguments)},cc=a._emscripten_bind_Node_set_m_area_1=function(){return(cc=a._emscripten_bind_Node_set_m_area_1=
a.asm.Ga).apply(null,arguments)},dc=a._emscripten_bind_Node___destroy___0=function(){return(dc=a._emscripten_bind_Node___destroy___0=a.asm.Ha).apply(null,arguments)},ec=a._emscripten_bind_tNodeArray_size_0=function(){return(ec=a._emscripten_bind_tNodeArray_size_0=a.asm.Ia).apply(null,arguments)},fc=a._emscripten_bind_tNodeArray_at_1=function(){return(fc=a._emscripten_bind_tNodeArray_at_1=a.asm.Ja).apply(null,arguments)},hc=a._emscripten_bind_tNodeArray___destroy___0=function(){return(hc=a._emscripten_bind_tNodeArray___destroy___0=
a.asm.Ka).apply(null,arguments)},ic=a._emscripten_bind_btSoftBodyArray_size_0=function(){return(ic=a._emscripten_bind_btSoftBodyArray_size_0=a.asm.La).apply(null,arguments)},jc=a._emscripten_bind_btSoftBodyArray_at_1=function(){return(jc=a._emscripten_bind_btSoftBodyArray_at_1=a.asm.Ma).apply(null,arguments)},kc=a._emscripten_bind_btSoftBodyArray___destroy___0=function(){return(kc=a._emscripten_bind_btSoftBodyArray___destroy___0=a.asm.Na).apply(null,arguments)},lc=a._emscripten_bind_btSoftBodyHelpers_btSoftBodyHelpers_0=
function(){return(lc=a._emscripten_bind_btSoftBodyHelpers_btSoftBodyHelpers_0=a.asm.Oa).apply(null,arguments)},mc=a._emscripten_bind_btSoftBodyHelpers_CreateFromTriMesh_5=function(){return(mc=a._emscripten_bind_btSoftBodyHelpers_CreateFromTriMesh_5=a.asm.Pa).apply(null,arguments)},nc=a._emscripten_bind_btSoftBodyHelpers___destroy___0=function(){return(nc=a._emscripten_bind_btSoftBodyHelpers___destroy___0=a.asm.Qa).apply(null,arguments)},oc=a._emscripten_bind_btSoftBodyWorldInfo_btSoftBodyWorldInfo_0=
function(){return(oc=a._emscripten_bind_btSoftBodyWorldInfo_btSoftBodyWorldInfo_0=a.asm.Ra).apply(null,arguments)},pc=a._emscripten_bind_btSoftBodyWorldInfo_get_m_gravity_0=function(){return(pc=a._emscripten_bind_btSoftBodyWorldInfo_get_m_gravity_0=a.asm.Sa).apply(null,arguments)},qc=a._emscripten_bind_btSoftBodyWorldInfo_set_m_gravity_1=function(){return(qc=a._emscripten_bind_btSoftBodyWorldInfo_set_m_gravity_1=a.asm.Ta).apply(null,arguments)},rc=a._emscripten_bind_btSoftBodyWorldInfo___destroy___0=
function(){return(rc=a._emscripten_bind_btSoftBodyWorldInfo___destroy___0=a.asm.Ua).apply(null,arguments)},sc=a._emscripten_bind_Face_get_m_n_1=function(){return(sc=a._emscripten_bind_Face_get_m_n_1=a.asm.Va).apply(null,arguments)},tc=a._emscripten_bind_Face_set_m_n_2=function(){return(tc=a._emscripten_bind_Face_set_m_n_2=a.asm.Wa).apply(null,arguments)},uc=a._emscripten_bind_Face_get_m_normal_0=function(){return(uc=a._emscripten_bind_Face_get_m_normal_0=a.asm.Xa).apply(null,arguments)},vc=a._emscripten_bind_Face_set_m_normal_1=
function(){return(vc=a._emscripten_bind_Face_set_m_normal_1=a.asm.Ya).apply(null,arguments)},wc=a._emscripten_bind_Face_get_m_ra_0=function(){return(wc=a._emscripten_bind_Face_get_m_ra_0=a.asm.Za).apply(null,arguments)},xc=a._emscripten_bind_Face_set_m_ra_1=function(){return(xc=a._emscripten_bind_Face_set_m_ra_1=a.asm._a).apply(null,arguments)},yc=a._emscripten_bind_Face___destroy___0=function(){return(yc=a._emscripten_bind_Face___destroy___0=a.asm.$a).apply(null,arguments)},zc=a._emscripten_bind_btVector3_btVector3_0=
function(){return(zc=a._emscripten_bind_btVector3_btVector3_0=a.asm.ab).apply(null,arguments)},Ac=a._emscripten_bind_btVector3_btVector3_3=function(){return(Ac=a._emscripten_bind_btVector3_btVector3_3=a.asm.bb).apply(null,arguments)},Bc=a._emscripten_bind_btVector3_dot_1=function(){return(Bc=a._emscripten_bind_btVector3_dot_1=a.asm.cb).apply(null,arguments)},Cc=a._emscripten_bind_btVector3_length_0=function(){return(Cc=a._emscripten_bind_btVector3_length_0=a.asm.db).apply(null,arguments)},Dc=a._emscripten_bind_btVector3_length2_0=
function(){return(Dc=a._emscripten_bind_btVector3_length2_0=a.asm.eb).apply(null,arguments)},Ec=a._emscripten_bind_btVector3_setX_1=function(){return(Ec=a._emscripten_bind_btVector3_setX_1=a.asm.fb).apply(null,arguments)},Fc=a._emscripten_bind_btVector3_setY_1=function(){return(Fc=a._emscripten_bind_btVector3_setY_1=a.asm.gb).apply(null,arguments)},Gc=a._emscripten_bind_btVector3_setZ_1=function(){return(Gc=a._emscripten_bind_btVector3_setZ_1=a.asm.hb).apply(null,arguments)},Hc=a._emscripten_bind_btVector3_setValue_3=
function(){return(Hc=a._emscripten_bind_btVector3_setValue_3=a.asm.ib).apply(null,arguments)},Ic=a._emscripten_bind_btVector3_x_0=function(){return(Ic=a._emscripten_bind_btVector3_x_0=a.asm.jb).apply(null,arguments)},Jc=a._emscripten_bind_btVector3_y_0=function(){return(Jc=a._emscripten_bind_btVector3_y_0=a.asm.kb).apply(null,arguments)},Kc=a._emscripten_bind_btVector3_z_0=function(){return(Kc=a._emscripten_bind_btVector3_z_0=a.asm.lb).apply(null,arguments)},Lc=a._emscripten_bind_btVector3_op_mul_1=
function(){return(Lc=a._emscripten_bind_btVector3_op_mul_1=a.asm.mb).apply(null,arguments)},Mc=a._emscripten_bind_btVector3_op_div_1=function(){return(Mc=a._emscripten_bind_btVector3_op_div_1=a.asm.nb).apply(null,arguments)},Nc=a._emscripten_bind_btVector3_op_add_1=function(){return(Nc=a._emscripten_bind_btVector3_op_add_1=a.asm.ob).apply(null,arguments)},Oc=a._emscripten_bind_btVector3_op_sub_1=function(){return(Oc=a._emscripten_bind_btVector3_op_sub_1=a.asm.pb).apply(null,arguments)},Pc=a._emscripten_bind_btVector3_get_m_floats_1=
function(){return(Pc=a._emscripten_bind_btVector3_get_m_floats_1=a.asm.qb).apply(null,arguments)},Qc=a._emscripten_bind_btVector3_set_m_floats_2=function(){return(Qc=a._emscripten_bind_btVector3_set_m_floats_2=a.asm.rb).apply(null,arguments)},Rc=a._emscripten_bind_btVector3___destroy___0=function(){return(Rc=a._emscripten_bind_btVector3___destroy___0=a.asm.sb).apply(null,arguments)},Sc=a._emscripten_bind_btSoftBody_btSoftBody_4=function(){return(Sc=a._emscripten_bind_btSoftBody_btSoftBody_4=a.asm.tb).apply(null,
arguments)},Tc=a._emscripten_bind_btSoftBody_generateBendingConstraints_1=function(){return(Tc=a._emscripten_bind_btSoftBody_generateBendingConstraints_1=a.asm.ub).apply(null,arguments)},Uc=a._emscripten_bind_btSoftBody_generateClusters_1=function(){return(Uc=a._emscripten_bind_btSoftBody_generateClusters_1=a.asm.vb).apply(null,arguments)},Vc=a._emscripten_bind_btSoftBody_generateClusters_2=function(){return(Vc=a._emscripten_bind_btSoftBody_generateClusters_2=a.asm.wb).apply(null,arguments)},Wc=a._emscripten_bind_btSoftBody_setTotalMass_1=
function(){return(Wc=a._emscripten_bind_btSoftBody_setTotalMass_1=a.asm.xb).apply(null,arguments)},Xc=a._emscripten_bind_btSoftBody_setTotalMass_2=function(){return(Xc=a._emscripten_bind_btSoftBody_setTotalMass_2=a.asm.yb).apply(null,arguments)},Yc=a._emscripten_bind_btSoftBody_setActivationState_1=function(){return(Yc=a._emscripten_bind_btSoftBody_setActivationState_1=a.asm.zb).apply(null,arguments)},Zc=a._emscripten_bind_btSoftBody_get_m_cfg_0=function(){return(Zc=a._emscripten_bind_btSoftBody_get_m_cfg_0=
a.asm.Ab).apply(null,arguments)},$c=a._emscripten_bind_btSoftBody_set_m_cfg_1=function(){return($c=a._emscripten_bind_btSoftBody_set_m_cfg_1=a.asm.Bb).apply(null,arguments)},ad=a._emscripten_bind_btSoftBody_get_m_nodes_0=function(){return(ad=a._emscripten_bind_btSoftBody_get_m_nodes_0=a.asm.Cb).apply(null,arguments)},bd=a._emscripten_bind_btSoftBody_set_m_nodes_1=function(){return(bd=a._emscripten_bind_btSoftBody_set_m_nodes_1=a.asm.Db).apply(null,arguments)},cd=a._emscripten_bind_btSoftBody_get_m_faces_0=
function(){return(cd=a._emscripten_bind_btSoftBody_get_m_faces_0=a.asm.Eb).apply(null,arguments)},dd=a._emscripten_bind_btSoftBody_set_m_faces_1=function(){return(dd=a._emscripten_bind_btSoftBody_set_m_faces_1=a.asm.Fb).apply(null,arguments)},ed=a._emscripten_bind_btSoftBody___destroy___0=function(){return(ed=a._emscripten_bind_btSoftBody___destroy___0=a.asm.Gb).apply(null,arguments)},fd=a._emscripten_bind_btSoftRigidDynamicsWorld_btSoftRigidDynamicsWorld_5=function(){return(fd=a._emscripten_bind_btSoftRigidDynamicsWorld_btSoftRigidDynamicsWorld_5=
a.asm.Hb).apply(null,arguments)},gd=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_1=function(){return(gd=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_1=a.asm.Ib).apply(null,arguments)},hd=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_2=function(){return(hd=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_2=a.asm.Jb).apply(null,arguments)},id=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_3=function(){return(id=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_3=
a.asm.Kb).apply(null,arguments)},jd=a._emscripten_bind_btSoftRigidDynamicsWorld_getWorldInfo_0=function(){return(jd=a._emscripten_bind_btSoftRigidDynamicsWorld_getWorldInfo_0=a.asm.Lb).apply(null,arguments)},kd=a._emscripten_bind_btSoftRigidDynamicsWorld_removeSoftBody_1=function(){return(kd=a._emscripten_bind_btSoftRigidDynamicsWorld_removeSoftBody_1=a.asm.Mb).apply(null,arguments)},ld=a._emscripten_bind_btSoftRigidDynamicsWorld_setGravity_1=function(){return(ld=a._emscripten_bind_btSoftRigidDynamicsWorld_setGravity_1=
a.asm.Nb).apply(null,arguments)},md=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_1=function(){return(md=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_1=a.asm.Ob).apply(null,arguments)},nd=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_2=function(){return(nd=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_2=a.asm.Pb).apply(null,arguments)},od=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_3=function(){return(od=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_3=
a.asm.Qb).apply(null,arguments)},pd=a._emscripten_bind_btSoftRigidDynamicsWorld___destroy___0=function(){return(pd=a._emscripten_bind_btSoftRigidDynamicsWorld___destroy___0=a.asm.Rb).apply(null,arguments)},qd=a._emscripten_bind_tFaceArray_size_0=function(){return(qd=a._emscripten_bind_tFaceArray_size_0=a.asm.Sb).apply(null,arguments)},rd=a._emscripten_bind_tFaceArray_at_1=function(){return(rd=a._emscripten_bind_tFaceArray_at_1=a.asm.Tb).apply(null,arguments)},sd=a._emscripten_bind_tFaceArray___destroy___0=
function(){return(sd=a._emscripten_bind_tFaceArray___destroy___0=a.asm.Ub).apply(null,arguments)},td=a._emscripten_bind_btSoftBodyRigidBodyCollisionConfiguration_btSoftBodyRigidBodyCollisionConfiguration_0=function(){return(td=a._emscripten_bind_btSoftBodyRigidBodyCollisionConfiguration_btSoftBodyRigidBodyCollisionConfiguration_0=a.asm.Vb).apply(null,arguments)},ud=a._emscripten_bind_btSoftBodyRigidBodyCollisionConfiguration___destroy___0=function(){return(ud=a._emscripten_bind_btSoftBodyRigidBodyCollisionConfiguration___destroy___0=
a.asm.Wb).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.Xb).apply(null,arguments)};a._free=function(){return(a._free=a.asm.Yb).apply(null,arguments)};a.dynCall_vi=function(){return(a.dynCall_vi=a.asm.Zb).apply(null,arguments)};a.dynCall_v=function(){return(a.dynCall_v=a.asm._b).apply(null,arguments)};var vd;x=function wd(){vd||xd();vd||(x=wd)};
function xd(){function b(){if(!vd&&(vd=!0,a.calledRun=!0,!ja)){oa(qa);oa(ra);aa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();sa.unshift(c)}oa(sa)}}if(!(0<w)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ta();oa(pa);0<w||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}
a.run=xd;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;xd();function z(){}z.prototype=Object.create(z.prototype);z.prototype.constructor=z;z.prototype.ac=z;z.bc={};a.WrapperObject=z;function A(b){return(b||z).bc}a.getCache=A;function B(b,c){var e=A(c),g=e[b];if(g)return g;g=Object.create((c||z).prototype);g.$b=b;return e[b]=g}a.wrapPointer=B;a.castObject=function(b,c){return B(b.$b,c)};a.NULL=B(0);
a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete A(b.ac)[b.$b]};a.compare=function(b,c){return b.$b===c.$b};a.getPointer=function(b){return b.$b};a.getClass=function(b){return b.ac};var C=0,yd=0,Ad=0,Bd=[],Cd=0;function Dd(){if(Cd){for(var b=0;b<Bd.length;b++)a._free(Bd[b]);Bd.length=0;a._free(C);C=0;yd+=Cd;Cd=0}C||(yd+=128,C=a._malloc(yd),assert(C));Ad=0}
function Ed(b,c){assert(C);b=b.length*c.BYTES_PER_ELEMENT;b=b+7&-8;Ad+b>=yd?(assert(0<b),Cd+=b,c=a._malloc(b),Bd.push(c)):(c=C+Ad,Ad+=b);return c}function Fd(b,c,e){e>>>=0;switch(c.BYTES_PER_ELEMENT){case 2:e>>>=1;break;case 4:e>>>=2;break;case 8:e>>>=3}for(var g=0;g<b.length;g++)c[e+g]=b[g]}function Gd(b){if("object"===typeof b){var c=Ed(b,ma);Fd(b,ma,c);return c}return b}function D(){throw"cannot construct a btCollisionObject, no constructor in IDL";}D.prototype=Object.create(z.prototype);
D.prototype.constructor=D;D.prototype.ac=D;D.bc={};a.btCollisionObject=D;D.prototype.setActivationState=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Ca(c,b)};D.prototype.__destroy__=function(){Da(this.$b)};function E(){throw"cannot construct a btDispatcher, no constructor in IDL";}E.prototype=Object.create(z.prototype);E.prototype.constructor=E;E.prototype.ac=E;E.bc={};a.btDispatcher=E;E.prototype.__destroy__=function(){Ea(this.$b)};
function F(){throw"cannot construct a btCollisionConfiguration, no constructor in IDL";}F.prototype=Object.create(z.prototype);F.prototype.constructor=F;F.prototype.ac=F;F.bc={};a.btCollisionConfiguration=F;F.prototype.__destroy__=function(){Fa(this.$b)};function G(){throw"cannot construct a btSoftBodySolver, no constructor in IDL";}G.prototype=Object.create(z.prototype);G.prototype.constructor=G;G.prototype.ac=G;G.bc={};a.btSoftBodySolver=G;G.prototype.__destroy__=function(){Ga(this.$b)};
function H(){throw"cannot construct a btBroadphaseInterface, no constructor in IDL";}H.prototype=Object.create(z.prototype);H.prototype.constructor=H;H.prototype.ac=H;H.bc={};a.btBroadphaseInterface=H;H.prototype.__destroy__=function(){Ha(this.$b)};function I(){throw"cannot construct a btConstraintSolver, no constructor in IDL";}I.prototype=Object.create(z.prototype);I.prototype.constructor=I;I.prototype.ac=I;I.bc={};a.btConstraintSolver=I;I.prototype.__destroy__=function(){Ia(this.$b)};
function J(){this.$b=Ja();A(J)[this.$b]=this}J.prototype=Object.create(H.prototype);J.prototype.constructor=J;J.prototype.ac=J;J.bc={};a.btDbvtBroadphase=J;J.prototype.__destroy__=function(){Ka(this.$b)};function K(){this.$b=La();A(K)[this.$b]=this}K.prototype=Object.create(G.prototype);K.prototype.constructor=K;K.prototype.ac=K;K.bc={};a.btDefaultSoftBodySolver=K;K.prototype.__destroy__=function(){Ma(this.$b)};function M(b){b&&"object"===typeof b&&(b=b.$b);this.$b=Na(b);A(M)[this.$b]=this}
M.prototype=Object.create(E.prototype);M.prototype.constructor=M;M.prototype.ac=M;M.bc={};a.btCollisionDispatcher=M;M.prototype.__destroy__=function(){Oa(this.$b)};function N(){this.$b=Pa();A(N)[this.$b]=this}N.prototype=Object.create(I.prototype);N.prototype.constructor=N;N.prototype.ac=N;N.bc={};a.btSequentialImpulseConstraintSolver=N;N.prototype.__destroy__=function(){Qa(this.$b)};function O(){throw"cannot construct a VoidPtr, no constructor in IDL";}O.prototype=Object.create(z.prototype);
O.prototype.constructor=O;O.prototype.ac=O;O.bc={};a.VoidPtr=O;O.prototype.__destroy__=function(){Ra(this.$b)};function P(){throw"cannot construct a Config, no constructor in IDL";}P.prototype=Object.create(z.prototype);P.prototype.constructor=P;P.prototype.ac=P;P.bc={};a.Config=P;P.prototype.get_kVCF=P.prototype.Bc=function(){return Sa(this.$b)};P.prototype.set_kVCF=P.prototype.od=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Ta(c,b)};
Object.defineProperty(P.prototype,"kVCF",{get:P.prototype.Bc,set:P.prototype.od});P.prototype.get_kDP=P.prototype.oc=function(){return Ua(this.$b)};P.prototype.set_kDP=P.prototype.$c=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Va(c,b)};Object.defineProperty(P.prototype,"kDP",{get:P.prototype.oc,set:P.prototype.$c});P.prototype.get_kDG=P.prototype.nc=function(){return Wa(this.$b)};P.prototype.set_kDG=P.prototype.Zc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Xa(c,b)};
Object.defineProperty(P.prototype,"kDG",{get:P.prototype.nc,set:P.prototype.Zc});P.prototype.get_kLF=P.prototype.qc=function(){return Ya(this.$b)};P.prototype.set_kLF=P.prototype.bd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Za(c,b)};Object.defineProperty(P.prototype,"kLF",{get:P.prototype.qc,set:P.prototype.bd});P.prototype.get_kPR=P.prototype.sc=function(){return $a(this.$b)};P.prototype.set_kPR=P.prototype.dd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);ab(c,b)};
Object.defineProperty(P.prototype,"kPR",{get:P.prototype.sc,set:P.prototype.dd});P.prototype.get_kVC=P.prototype.Ac=function(){return bb(this.$b)};P.prototype.set_kVC=P.prototype.nd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);cb(c,b)};Object.defineProperty(P.prototype,"kVC",{get:P.prototype.Ac,set:P.prototype.nd});P.prototype.get_kDF=P.prototype.mc=function(){return db(this.$b)};P.prototype.set_kDF=P.prototype.Yc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);eb(c,b)};
Object.defineProperty(P.prototype,"kDF",{get:P.prototype.mc,set:P.prototype.Yc});P.prototype.get_kMT=P.prototype.rc=function(){return fb(this.$b)};P.prototype.set_kMT=P.prototype.cd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);gb(c,b)};Object.defineProperty(P.prototype,"kMT",{get:P.prototype.rc,set:P.prototype.cd});P.prototype.get_kCHR=P.prototype.lc=function(){return hb(this.$b)};P.prototype.set_kCHR=P.prototype.Xc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);ib(c,b)};
Object.defineProperty(P.prototype,"kCHR",{get:P.prototype.lc,set:P.prototype.Xc});P.prototype.get_kKHR=P.prototype.pc=function(){return jb(this.$b)};P.prototype.set_kKHR=P.prototype.ad=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);kb(c,b)};Object.defineProperty(P.prototype,"kKHR",{get:P.prototype.pc,set:P.prototype.ad});P.prototype.get_kSHR=P.prototype.tc=function(){return lb(this.$b)};
P.prototype.set_kSHR=P.prototype.ed=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);mb(c,b)};Object.defineProperty(P.prototype,"kSHR",{get:P.prototype.tc,set:P.prototype.ed});P.prototype.get_kAHR=P.prototype.kc=function(){return nb(this.$b)};P.prototype.set_kAHR=P.prototype.Wc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);ob(c,b)};Object.defineProperty(P.prototype,"kAHR",{get:P.prototype.kc,set:P.prototype.Wc});P.prototype.get_kSRHR_CL=P.prototype.wc=function(){return pb(this.$b)};
P.prototype.set_kSRHR_CL=P.prototype.jd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);qb(c,b)};Object.defineProperty(P.prototype,"kSRHR_CL",{get:P.prototype.wc,set:P.prototype.jd});P.prototype.get_kSKHR_CL=P.prototype.uc=function(){return rb(this.$b)};P.prototype.set_kSKHR_CL=P.prototype.gd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);sb(c,b)};Object.defineProperty(P.prototype,"kSKHR_CL",{get:P.prototype.uc,set:P.prototype.gd});P.prototype.get_kSSHR_CL=P.prototype.yc=function(){return tb(this.$b)};
P.prototype.set_kSSHR_CL=P.prototype.ld=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);ub(c,b)};Object.defineProperty(P.prototype,"kSSHR_CL",{get:P.prototype.yc,set:P.prototype.ld});P.prototype.get_kSR_SPLT_CL=P.prototype.xc=function(){return vb(this.$b)};P.prototype.set_kSR_SPLT_CL=P.prototype.kd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);wb(c,b)};Object.defineProperty(P.prototype,"kSR_SPLT_CL",{get:P.prototype.xc,set:P.prototype.kd});
P.prototype.get_kSK_SPLT_CL=P.prototype.vc=function(){return xb(this.$b)};P.prototype.set_kSK_SPLT_CL=P.prototype.hd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);yb(c,b)};Object.defineProperty(P.prototype,"kSK_SPLT_CL",{get:P.prototype.vc,set:P.prototype.hd});P.prototype.get_kSS_SPLT_CL=P.prototype.zc=function(){return zb(this.$b)};P.prototype.set_kSS_SPLT_CL=P.prototype.md=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Ab(c,b)};
Object.defineProperty(P.prototype,"kSS_SPLT_CL",{get:P.prototype.zc,set:P.prototype.md});P.prototype.get_maxvolume=P.prototype.Pc=function(){return Bb(this.$b)};P.prototype.set_maxvolume=P.prototype.Cd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Cb(c,b)};Object.defineProperty(P.prototype,"maxvolume",{get:P.prototype.Pc,set:P.prototype.Cd});P.prototype.get_timescale=P.prototype.Rc=function(){return Db(this.$b)};
P.prototype.set_timescale=P.prototype.Ed=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Eb(c,b)};Object.defineProperty(P.prototype,"timescale",{get:P.prototype.Rc,set:P.prototype.Ed});P.prototype.get_viterations=P.prototype.Sc=function(){return Fb(this.$b)};P.prototype.set_viterations=P.prototype.Fd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Gb(c,b)};Object.defineProperty(P.prototype,"viterations",{get:P.prototype.Sc,set:P.prototype.Fd});
P.prototype.get_piterations=P.prototype.Qc=function(){return Hb(this.$b)};P.prototype.set_piterations=P.prototype.Dd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Ib(c,b)};Object.defineProperty(P.prototype,"piterations",{get:P.prototype.Qc,set:P.prototype.Dd});P.prototype.get_diterations=P.prototype.jc=function(){return Jb(this.$b)};P.prototype.set_diterations=P.prototype.Vc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Kb(c,b)};
Object.defineProperty(P.prototype,"diterations",{get:P.prototype.jc,set:P.prototype.Vc});P.prototype.get_citerations=P.prototype.hc=function(){return Lb(this.$b)};P.prototype.set_citerations=P.prototype.Tc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Mb(c,b)};Object.defineProperty(P.prototype,"citerations",{get:P.prototype.hc,set:P.prototype.Tc});P.prototype.get_collisions=P.prototype.ic=function(){return Nb(this.$b)};
P.prototype.set_collisions=P.prototype.Uc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Ob(c,b)};Object.defineProperty(P.prototype,"collisions",{get:P.prototype.ic,set:P.prototype.Uc});P.prototype.__destroy__=function(){Pb(this.$b)};function Node(){throw"cannot construct a Node, no constructor in IDL";}Node.prototype=Object.create(z.prototype);Node.prototype.constructor=Node;Node.prototype.ac=Node;Node.bc={};a.Node=Node;
Node.prototype.get_m_x=Node.prototype.Oc=function(){return B(Qb(this.$b),Q)};Node.prototype.set_m_x=Node.prototype.Bd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Rb(c,b)};Object.defineProperty(Node.prototype,"m_x",{get:Node.prototype.Oc,set:Node.prototype.Bd});Node.prototype.get_m_q=Node.prototype.Lc=function(){return B(Sb(this.$b),Q)};Node.prototype.set_m_q=Node.prototype.yd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Tb(c,b)};
Object.defineProperty(Node.prototype,"m_q",{get:Node.prototype.Lc,set:Node.prototype.yd});Node.prototype.get_m_v=Node.prototype.Nc=function(){return B(Ub(this.$b),Q)};Node.prototype.set_m_v=Node.prototype.Ad=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Vb(c,b)};Object.defineProperty(Node.prototype,"m_v",{get:Node.prototype.Nc,set:Node.prototype.Ad});Node.prototype.get_m_f=Node.prototype.Ec=function(){return B(Wb(this.$b),Q)};
Node.prototype.set_m_f=Node.prototype.rd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Xb(c,b)};Object.defineProperty(Node.prototype,"m_f",{get:Node.prototype.Ec,set:Node.prototype.rd});Node.prototype.get_m_n=Node.prototype.dc=function(){return B(Yb(this.$b),Q)};Node.prototype.set_m_n=Node.prototype.ec=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Zb(c,b)};Object.defineProperty(Node.prototype,"m_n",{get:Node.prototype.dc,set:Node.prototype.ec});
Node.prototype.get_m_im=Node.prototype.Ic=function(){return $b(this.$b)};Node.prototype.set_m_im=Node.prototype.vd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);ac(c,b)};Object.defineProperty(Node.prototype,"m_im",{get:Node.prototype.Ic,set:Node.prototype.vd});Node.prototype.get_m_area=Node.prototype.Cc=function(){return bc(this.$b)};Node.prototype.set_m_area=Node.prototype.pd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);cc(c,b)};
Object.defineProperty(Node.prototype,"m_area",{get:Node.prototype.Cc,set:Node.prototype.pd});Node.prototype.__destroy__=function(){dc(this.$b)};function R(){throw"cannot construct a tNodeArray, no constructor in IDL";}R.prototype=Object.create(z.prototype);R.prototype.constructor=R;R.prototype.ac=R;R.bc={};a.tNodeArray=R;R.prototype.size=R.prototype.size=function(){return ec(this.$b)};R.prototype.at=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return B(fc(c,b),Node)};
R.prototype.__destroy__=function(){hc(this.$b)};function S(){throw"cannot construct a btSoftBodyArray, no constructor in IDL";}S.prototype=Object.create(z.prototype);S.prototype.constructor=S;S.prototype.ac=S;S.bc={};a.btSoftBodyArray=S;S.prototype.size=S.prototype.size=function(){return ic(this.$b)};S.prototype.at=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return B(jc(c,b),T)};S.prototype.__destroy__=function(){kc(this.$b)};function U(){this.$b=lc();A(U)[this.$b]=this}
U.prototype=Object.create(z.prototype);U.prototype.constructor=U;U.prototype.ac=U;U.bc={};a.btSoftBodyHelpers=U;U.prototype.CreateFromTriMesh=function(b,c,e,g,m){var L=this.$b;Dd();b&&"object"===typeof b&&(b=b.$b);"object"==typeof c&&(c=Gd(c));if("object"==typeof e&&"object"===typeof e){var zd=Ed(e,u);Fd(e,u,zd);e=zd}g&&"object"===typeof g&&(g=g.$b);m&&"object"===typeof m&&(m=m.$b);return B(mc(L,b,c,e,g,m),T)};U.prototype.__destroy__=function(){nc(this.$b)};
function V(){this.$b=oc();A(V)[this.$b]=this}V.prototype=Object.create(z.prototype);V.prototype.constructor=V;V.prototype.ac=V;V.bc={};a.btSoftBodyWorldInfo=V;V.prototype.get_m_gravity=V.prototype.Hc=function(){return B(pc(this.$b),Q)};V.prototype.set_m_gravity=V.prototype.ud=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);qc(c,b)};Object.defineProperty(V.prototype,"m_gravity",{get:V.prototype.Hc,set:V.prototype.ud});V.prototype.__destroy__=function(){rc(this.$b)};
function W(){throw"cannot construct a Face, no constructor in IDL";}W.prototype=Object.create(z.prototype);W.prototype.constructor=W;W.prototype.ac=W;W.bc={};a.Face=W;W.prototype.get_m_n=W.prototype.dc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return B(sc(c,b),Node)};W.prototype.set_m_n=W.prototype.ec=function(b,c){var e=this.$b;Dd();b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);tc(e,b,c)};Object.defineProperty(W.prototype,"m_n",{get:W.prototype.dc,set:W.prototype.ec});
W.prototype.get_m_normal=W.prototype.Kc=function(){return B(uc(this.$b),Q)};W.prototype.set_m_normal=W.prototype.xd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);vc(c,b)};Object.defineProperty(W.prototype,"m_normal",{get:W.prototype.Kc,set:W.prototype.xd});W.prototype.get_m_ra=W.prototype.Mc=function(){return wc(this.$b)};W.prototype.set_m_ra=W.prototype.zd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);xc(c,b)};
Object.defineProperty(W.prototype,"m_ra",{get:W.prototype.Mc,set:W.prototype.zd});W.prototype.__destroy__=function(){yc(this.$b)};function Q(b,c,e){b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);e&&"object"===typeof e&&(e=e.$b);this.$b=void 0===b?zc():void 0===c?_emscripten_bind_btVector3_btVector3_1(b):void 0===e?_emscripten_bind_btVector3_btVector3_2(b,c):Ac(b,c,e);A(Q)[this.$b]=this}Q.prototype=Object.create(z.prototype);Q.prototype.constructor=Q;Q.prototype.ac=Q;Q.bc={};
a.btVector3=Q;Q.prototype.dot=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return Bc(c,b)};Q.prototype.length=Q.prototype.length=function(){return Cc(this.$b)};Q.prototype.length2=function(){return Dc(this.$b)};Q.prototype.setX=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Ec(c,b)};Q.prototype.setY=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Fc(c,b)};Q.prototype.setZ=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Gc(c,b)};
Q.prototype.setValue=function(b,c,e){var g=this.$b;b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);e&&"object"===typeof e&&(e=e.$b);Hc(g,b,c,e)};Q.prototype.x=Q.prototype.x=function(){return Ic(this.$b)};Q.prototype.y=Q.prototype.y=function(){return Jc(this.$b)};Q.prototype.z=Q.prototype.z=function(){return Kc(this.$b)};Q.prototype.op_mul=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return B(Lc(c,b),Q)};
Q.prototype.op_div=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return B(Mc(c,b),Q)};Q.prototype.op_add=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return B(Nc(c,b),Q)};Q.prototype.op_sub=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return B(Oc(c,b),Q)};Q.prototype.get_m_floats=Q.prototype.Gc=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return Pc(c,b)};
Q.prototype.set_m_floats=Q.prototype.td=function(b,c){var e=this.$b;Dd();b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);Qc(e,b,c)};Object.defineProperty(Q.prototype,"m_floats",{get:Q.prototype.Gc,set:Q.prototype.td});Q.prototype.__destroy__=function(){Rc(this.$b)};function T(b,c,e,g){Dd();b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);e&&"object"===typeof e&&(e=e.$b);"object"==typeof g&&(g=Gd(g));this.$b=Sc(b,c,e,g);A(T)[this.$b]=this}T.prototype=Object.create(D.prototype);
T.prototype.constructor=T;T.prototype.ac=T;T.bc={};a.btSoftBody=T;T.prototype.generateBendingConstraints=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return Tc(c,b)};T.prototype.generateClusters=function(b,c){var e=this.$b;b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);return void 0===c?Uc(e,b):Vc(e,b,c)};T.prototype.setTotalMass=function(b,c){var e=this.$b;b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);void 0===c?Wc(e,b):Xc(e,b,c)};
T.prototype.setActivationState=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);Yc(c,b)};T.prototype.get_m_cfg=T.prototype.Dc=function(){return B(Zc(this.$b),P)};T.prototype.set_m_cfg=T.prototype.qd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);$c(c,b)};Object.defineProperty(T.prototype,"m_cfg",{get:T.prototype.Dc,set:T.prototype.qd});T.prototype.get_m_nodes=T.prototype.Jc=function(){return B(ad(this.$b),R)};
T.prototype.set_m_nodes=T.prototype.wd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);bd(c,b)};Object.defineProperty(T.prototype,"m_nodes",{get:T.prototype.Jc,set:T.prototype.wd});T.prototype.get_m_faces=T.prototype.Fc=function(){return B(cd(this.$b),X)};T.prototype.set_m_faces=T.prototype.sd=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);dd(c,b)};Object.defineProperty(T.prototype,"m_faces",{get:T.prototype.Fc,set:T.prototype.sd});T.prototype.__destroy__=function(){ed(this.$b)};
function Y(b,c,e,g,m){b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);e&&"object"===typeof e&&(e=e.$b);g&&"object"===typeof g&&(g=g.$b);m&&"object"===typeof m&&(m=m.$b);this.$b=fd(b,c,e,g,m);A(Y)[this.$b]=this}Y.prototype=Object.create(z.prototype);Y.prototype.constructor=Y;Y.prototype.ac=Y;Y.bc={};a.btSoftRigidDynamicsWorld=Y;
Y.prototype.addSoftBody=function(b,c,e){var g=this.$b;b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);e&&"object"===typeof e&&(e=e.$b);void 0===c?gd(g,b):void 0===e?hd(g,b,c):id(g,b,c,e)};Y.prototype.getWorldInfo=function(){return B(jd(this.$b),V)};Y.prototype.removeSoftBody=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);kd(c,b)};Y.prototype.setGravity=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);ld(c,b)};
Y.prototype.stepSimulation=function(b,c,e){var g=this.$b;b&&"object"===typeof b&&(b=b.$b);c&&"object"===typeof c&&(c=c.$b);e&&"object"===typeof e&&(e=e.$b);return void 0===c?md(g,b):void 0===e?nd(g,b,c):od(g,b,c,e)};Y.prototype.__destroy__=function(){pd(this.$b)};function X(){throw"cannot construct a tFaceArray, no constructor in IDL";}X.prototype=Object.create(z.prototype);X.prototype.constructor=X;X.prototype.ac=X;X.bc={};a.tFaceArray=X;X.prototype.size=X.prototype.size=function(){return qd(this.$b)};
X.prototype.at=function(b){var c=this.$b;b&&"object"===typeof b&&(b=b.$b);return B(rd(c,b),W)};X.prototype.__destroy__=function(){sd(this.$b)};function Z(){this.$b=td();A(Z)[this.$b]=this}Z.prototype=Object.create(F.prototype);Z.prototype.constructor=Z;Z.prototype.ac=Z;Z.bc={};a.btSoftBodyRigidBodyCollisionConfiguration=Z;Z.prototype.__destroy__=function(){ud(this.$b)};this.Ammo=a;


  return Ammo.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Ammo;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Ammo; });
    else if (typeof exports === 'object')
      exports["Ammo"] = Ammo;
    