
// This is ammo.js, a port of Bullet Physics to JavaScript. zlib licensed.

var Ammo = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Ammo) {
  Ammo = Ammo || {};


var a;a||(a=typeof Ammo !== 'undefined' ? Ammo : {});var aa;a.ready=new Promise(function(b){aa=b});var e={},g;for(g in a)a.hasOwnProperty(g)&&(e[g]=a[g]);var h=!1,k=!1,ba=!1,ca=!1;h="object"===typeof window;k="function"===typeof importScripts;ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!h&&!ba&&!k;var l="",n,p,da,ea;
if(ba)l=k?require("path").dirname(l)+"/":__dirname+"/",n=function(b,c){da||(da=require("fs"));ea||(ea=require("path"));b=ea.normalize(b);return da.readFileSync(b,c?null:"utf8")},p=function(b){b=n(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",q),a.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=
typeof read&&(n=function(b){return read(b)}),p=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"===typeof b);return b},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(h||k)k?l=self.location.href:document.currentScript&&(l=document.currentScript.src),_scriptDir&&(l=_scriptDir),l=0!==l.indexOf("blob:")?l.substr(0,
l.lastIndexOf("/")+1):"",n=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},k&&(p=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var fa=a.print||console.log.bind(console),r=a.printErr||console.warn.bind(console);for(g in e)e.hasOwnProperty(g)&&(a[g]=e[g]);e=null;var t;a.wasmBinary&&(t=a.wasmBinary);var noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);
"object"!==typeof WebAssembly&&r("no native wasm support detected");var ha,ia=new WebAssembly.Table({initial:535,maximum:535,element:"anyfunc"}),ja=!1;function assert(b,c){b||q("Assertion failed: "+c)}var ka,la,u,ma,na=a.INITIAL_MEMORY||16777216;if(ha=a.wasmMemory?a.wasmMemory:new WebAssembly.Memory({initial:na/65536,maximum:na/65536}))ka=ha.buffer;na=ka.byteLength;var v=ka;ka=v;a.HEAP8=new Int8Array(v);a.HEAP16=new Int16Array(v);a.HEAP32=u=new Int32Array(v);a.HEAPU8=la=new Uint8Array(v);
a.HEAPU16=new Uint16Array(v);a.HEAPU32=new Uint32Array(v);a.HEAPF32=ma=new Float32Array(v);a.HEAPF64=new Float64Array(v);u[4908]=5262672;function oa(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var d=c.gb;"number"===typeof d?void 0===c.fb?a.dynCall_v(d):a.dynCall_vi(d,c.fb):d(void 0===c.fb?null:c.fb)}}}var pa=[],qa=[],ra=[],sa=[];function ta(){var b=a.preRun.shift();pa.unshift(b)}var w=0,ua=null,x=null;a.preloadedImages={};a.preloadedAudios={};
function q(b){if(a.onAbort)a.onAbort(b);b+="";fa(b);r(b);ja=!0;throw new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function va(b){var c=y;return String.prototype.startsWith?c.startsWith(b):0===c.indexOf(b)}function wa(){return va("data:application/octet-stream;base64,")}var y="ammo.wasm.wasm";if(!wa()){var xa=y;y=a.locateFile?a.locateFile(xa,l):l+xa}
function ya(){try{if(t)return new Uint8Array(t);if(p)return p(y);throw"both async and sync fetching of the wasm failed";}catch(b){q(b)}}function za(){return t||!h&&!k||"function"!==typeof fetch||va("file://")?new Promise(function(b){b(ya())}):fetch(y,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+y+"'";return b.arrayBuffer()}).catch(function(){return ya()})}qa.push({gb:function(){Aa()}});
var Ba={d:function(){q()},b:function(b,c,d){la.copyWithin(b,c,c+d)},c:function(){q("OOM")},a:function(b){var c=Date.now();u[b>>2]=c/1E3|0;u[b+4>>2]=c%1E3*1E3|0;return 0},memory:ha,table:ia};
(function(){function b(m){a.asm=m.exports;w--;a.monitorRunDependencies&&a.monitorRunDependencies(w);0==w&&(null!==ua&&(clearInterval(ua),ua=null),x&&(m=x,x=null,m()))}function c(m){b(m.instance)}function d(m){return za().then(function(L){return WebAssembly.instantiate(L,f)}).then(m,function(L){r("failed to asynchronously prepare wasm: "+L);q(L)})}var f={a:Ba};w++;a.monitorRunDependencies&&a.monitorRunDependencies(w);if(a.instantiateWasm)try{return a.instantiateWasm(f,b)}catch(m){return r("Module.instantiateWasm callback failed with error: "+
m),!1}(function(){if(t||"function"!==typeof WebAssembly.instantiateStreaming||wa()||va("file://")||"function"!==typeof fetch)return d(c);fetch(y,{credentials:"same-origin"}).then(function(m){return WebAssembly.instantiateStreaming(m,f).then(c,function(L){r("wasm streaming compile failed: "+L);r("falling back to ArrayBuffer instantiation");return d(c)})})})();return{}})();var Aa=a.___wasm_call_ctors=function(){return(Aa=a.___wasm_call_ctors=a.asm.e).apply(null,arguments)};
a.___em_js__array_bounds_check_error=function(){return(a.___em_js__array_bounds_check_error=a.asm.f).apply(null,arguments)};
var Ca=a._emscripten_bind_btCollisionObject_setActivationState_1=function(){return(Ca=a._emscripten_bind_btCollisionObject_setActivationState_1=a.asm.g).apply(null,arguments)},Da=a._emscripten_bind_btCollisionObject___destroy___0=function(){return(Da=a._emscripten_bind_btCollisionObject___destroy___0=a.asm.h).apply(null,arguments)},Ea=a._emscripten_bind_btDispatcher___destroy___0=function(){return(Ea=a._emscripten_bind_btDispatcher___destroy___0=a.asm.i).apply(null,arguments)},Fa=a._emscripten_bind_btCollisionConfiguration___destroy___0=
function(){return(Fa=a._emscripten_bind_btCollisionConfiguration___destroy___0=a.asm.j).apply(null,arguments)},Ga=a._emscripten_bind_btSoftBodySolver___destroy___0=function(){return(Ga=a._emscripten_bind_btSoftBodySolver___destroy___0=a.asm.k).apply(null,arguments)},Ha=a._emscripten_bind_btBroadphaseInterface___destroy___0=function(){return(Ha=a._emscripten_bind_btBroadphaseInterface___destroy___0=a.asm.l).apply(null,arguments)},Ia=a._emscripten_bind_btConstraintSolver___destroy___0=function(){return(Ia=
a._emscripten_bind_btConstraintSolver___destroy___0=a.asm.m).apply(null,arguments)},Ja=a._emscripten_bind_btDbvtBroadphase_btDbvtBroadphase_0=function(){return(Ja=a._emscripten_bind_btDbvtBroadphase_btDbvtBroadphase_0=a.asm.n).apply(null,arguments)},Ka=a._emscripten_bind_btDbvtBroadphase___destroy___0=function(){return(Ka=a._emscripten_bind_btDbvtBroadphase___destroy___0=a.asm.o).apply(null,arguments)},La=a._emscripten_bind_btDefaultSoftBodySolver_btDefaultSoftBodySolver_0=function(){return(La=a._emscripten_bind_btDefaultSoftBodySolver_btDefaultSoftBodySolver_0=
a.asm.p).apply(null,arguments)},Ma=a._emscripten_bind_btDefaultSoftBodySolver___destroy___0=function(){return(Ma=a._emscripten_bind_btDefaultSoftBodySolver___destroy___0=a.asm.q).apply(null,arguments)},Na=a._emscripten_bind_btCollisionDispatcher_btCollisionDispatcher_1=function(){return(Na=a._emscripten_bind_btCollisionDispatcher_btCollisionDispatcher_1=a.asm.r).apply(null,arguments)},Oa=a._emscripten_bind_btCollisionDispatcher___destroy___0=function(){return(Oa=a._emscripten_bind_btCollisionDispatcher___destroy___0=
a.asm.s).apply(null,arguments)},Pa=a._emscripten_bind_btSequentialImpulseConstraintSolver_btSequentialImpulseConstraintSolver_0=function(){return(Pa=a._emscripten_bind_btSequentialImpulseConstraintSolver_btSequentialImpulseConstraintSolver_0=a.asm.t).apply(null,arguments)},Qa=a._emscripten_bind_btSequentialImpulseConstraintSolver___destroy___0=function(){return(Qa=a._emscripten_bind_btSequentialImpulseConstraintSolver___destroy___0=a.asm.u).apply(null,arguments)},Ra=a._emscripten_bind_VoidPtr___destroy___0=
function(){return(Ra=a._emscripten_bind_VoidPtr___destroy___0=a.asm.v).apply(null,arguments)},Sa=a._emscripten_bind_Config_get_timescale_0=function(){return(Sa=a._emscripten_bind_Config_get_timescale_0=a.asm.w).apply(null,arguments)},Ta=a._emscripten_bind_Config_set_timescale_1=function(){return(Ta=a._emscripten_bind_Config_set_timescale_1=a.asm.x).apply(null,arguments)},Ua=a._emscripten_bind_Config_get_viterations_0=function(){return(Ua=a._emscripten_bind_Config_get_viterations_0=a.asm.y).apply(null,
arguments)},Va=a._emscripten_bind_Config_set_viterations_1=function(){return(Va=a._emscripten_bind_Config_set_viterations_1=a.asm.z).apply(null,arguments)},Wa=a._emscripten_bind_Config_get_piterations_0=function(){return(Wa=a._emscripten_bind_Config_get_piterations_0=a.asm.A).apply(null,arguments)},Xa=a._emscripten_bind_Config_set_piterations_1=function(){return(Xa=a._emscripten_bind_Config_set_piterations_1=a.asm.B).apply(null,arguments)},Ya=a._emscripten_bind_Config_get_collisions_0=function(){return(Ya=
a._emscripten_bind_Config_get_collisions_0=a.asm.C).apply(null,arguments)},Za=a._emscripten_bind_Config_set_collisions_1=function(){return(Za=a._emscripten_bind_Config_set_collisions_1=a.asm.D).apply(null,arguments)},$a=a._emscripten_bind_Config___destroy___0=function(){return($a=a._emscripten_bind_Config___destroy___0=a.asm.E).apply(null,arguments)},ab=a._emscripten_bind_Node_get_m_x_0=function(){return(ab=a._emscripten_bind_Node_get_m_x_0=a.asm.F).apply(null,arguments)},bb=a._emscripten_bind_Node_set_m_x_1=
function(){return(bb=a._emscripten_bind_Node_set_m_x_1=a.asm.G).apply(null,arguments)},cb=a._emscripten_bind_Node_get_m_f_0=function(){return(cb=a._emscripten_bind_Node_get_m_f_0=a.asm.H).apply(null,arguments)},db=a._emscripten_bind_Node_set_m_f_1=function(){return(db=a._emscripten_bind_Node_set_m_f_1=a.asm.I).apply(null,arguments)},eb=a._emscripten_bind_Node___destroy___0=function(){return(eb=a._emscripten_bind_Node___destroy___0=a.asm.J).apply(null,arguments)},fb=a._emscripten_bind_tNodeArray_size_0=
function(){return(fb=a._emscripten_bind_tNodeArray_size_0=a.asm.K).apply(null,arguments)},gb=a._emscripten_bind_tNodeArray_at_1=function(){return(gb=a._emscripten_bind_tNodeArray_at_1=a.asm.L).apply(null,arguments)},hb=a._emscripten_bind_tNodeArray___destroy___0=function(){return(hb=a._emscripten_bind_tNodeArray___destroy___0=a.asm.M).apply(null,arguments)},ib=a._emscripten_bind_btSoftBodyArray_size_0=function(){return(ib=a._emscripten_bind_btSoftBodyArray_size_0=a.asm.N).apply(null,arguments)},jb=
a._emscripten_bind_btSoftBodyArray_at_1=function(){return(jb=a._emscripten_bind_btSoftBodyArray_at_1=a.asm.O).apply(null,arguments)},kb=a._emscripten_bind_btSoftBodyArray___destroy___0=function(){return(kb=a._emscripten_bind_btSoftBodyArray___destroy___0=a.asm.P).apply(null,arguments)},lb=a._emscripten_bind_btSoftBodyHelpers_btSoftBodyHelpers_0=function(){return(lb=a._emscripten_bind_btSoftBodyHelpers_btSoftBodyHelpers_0=a.asm.Q).apply(null,arguments)},mb=a._emscripten_bind_btSoftBodyHelpers_CreateFromTriMesh_5=
function(){return(mb=a._emscripten_bind_btSoftBodyHelpers_CreateFromTriMesh_5=a.asm.R).apply(null,arguments)},nb=a._emscripten_bind_btSoftBodyHelpers___destroy___0=function(){return(nb=a._emscripten_bind_btSoftBodyHelpers___destroy___0=a.asm.S).apply(null,arguments)},ob=a._emscripten_bind_btSoftBodyWorldInfo_btSoftBodyWorldInfo_0=function(){return(ob=a._emscripten_bind_btSoftBodyWorldInfo_btSoftBodyWorldInfo_0=a.asm.T).apply(null,arguments)},pb=a._emscripten_bind_btSoftBodyWorldInfo_get_m_gravity_0=
function(){return(pb=a._emscripten_bind_btSoftBodyWorldInfo_get_m_gravity_0=a.asm.U).apply(null,arguments)},qb=a._emscripten_bind_btSoftBodyWorldInfo_set_m_gravity_1=function(){return(qb=a._emscripten_bind_btSoftBodyWorldInfo_set_m_gravity_1=a.asm.V).apply(null,arguments)},rb=a._emscripten_bind_btSoftBodyWorldInfo___destroy___0=function(){return(rb=a._emscripten_bind_btSoftBodyWorldInfo___destroy___0=a.asm.W).apply(null,arguments)},sb=a._emscripten_bind_Face_get_m_n_1=function(){return(sb=a._emscripten_bind_Face_get_m_n_1=
a.asm.X).apply(null,arguments)},tb=a._emscripten_bind_Face_set_m_n_2=function(){return(tb=a._emscripten_bind_Face_set_m_n_2=a.asm.Y).apply(null,arguments)},ub=a._emscripten_bind_Face_get_m_normal_0=function(){return(ub=a._emscripten_bind_Face_get_m_normal_0=a.asm.Z).apply(null,arguments)},vb=a._emscripten_bind_Face_set_m_normal_1=function(){return(vb=a._emscripten_bind_Face_set_m_normal_1=a.asm._).apply(null,arguments)},wb=a._emscripten_bind_Face_get_m_ra_0=function(){return(wb=a._emscripten_bind_Face_get_m_ra_0=
a.asm.$).apply(null,arguments)},xb=a._emscripten_bind_Face_set_m_ra_1=function(){return(xb=a._emscripten_bind_Face_set_m_ra_1=a.asm.aa).apply(null,arguments)},yb=a._emscripten_bind_Face___destroy___0=function(){return(yb=a._emscripten_bind_Face___destroy___0=a.asm.ba).apply(null,arguments)},zb=a._emscripten_bind_btVector3_btVector3_0=function(){return(zb=a._emscripten_bind_btVector3_btVector3_0=a.asm.ca).apply(null,arguments)},Ab=a._emscripten_bind_btVector3_btVector3_3=function(){return(Ab=a._emscripten_bind_btVector3_btVector3_3=
a.asm.da).apply(null,arguments)},Bb=a._emscripten_bind_btVector3_dot_1=function(){return(Bb=a._emscripten_bind_btVector3_dot_1=a.asm.ea).apply(null,arguments)},Cb=a._emscripten_bind_btVector3_length_0=function(){return(Cb=a._emscripten_bind_btVector3_length_0=a.asm.fa).apply(null,arguments)},Db=a._emscripten_bind_btVector3_length2_0=function(){return(Db=a._emscripten_bind_btVector3_length2_0=a.asm.ga).apply(null,arguments)},Eb=a._emscripten_bind_btVector3_setX_1=function(){return(Eb=a._emscripten_bind_btVector3_setX_1=
a.asm.ha).apply(null,arguments)},Fb=a._emscripten_bind_btVector3_setY_1=function(){return(Fb=a._emscripten_bind_btVector3_setY_1=a.asm.ia).apply(null,arguments)},Gb=a._emscripten_bind_btVector3_setZ_1=function(){return(Gb=a._emscripten_bind_btVector3_setZ_1=a.asm.ja).apply(null,arguments)},Hb=a._emscripten_bind_btVector3_setValue_3=function(){return(Hb=a._emscripten_bind_btVector3_setValue_3=a.asm.ka).apply(null,arguments)},Ib=a._emscripten_bind_btVector3_x_0=function(){return(Ib=a._emscripten_bind_btVector3_x_0=
a.asm.la).apply(null,arguments)},Jb=a._emscripten_bind_btVector3_y_0=function(){return(Jb=a._emscripten_bind_btVector3_y_0=a.asm.ma).apply(null,arguments)},Kb=a._emscripten_bind_btVector3_z_0=function(){return(Kb=a._emscripten_bind_btVector3_z_0=a.asm.na).apply(null,arguments)},Lb=a._emscripten_bind_btVector3_op_mul_1=function(){return(Lb=a._emscripten_bind_btVector3_op_mul_1=a.asm.oa).apply(null,arguments)},Mb=a._emscripten_bind_btVector3_op_div_1=function(){return(Mb=a._emscripten_bind_btVector3_op_div_1=
a.asm.pa).apply(null,arguments)},Nb=a._emscripten_bind_btVector3_op_add_1=function(){return(Nb=a._emscripten_bind_btVector3_op_add_1=a.asm.qa).apply(null,arguments)},Ob=a._emscripten_bind_btVector3_op_sub_1=function(){return(Ob=a._emscripten_bind_btVector3_op_sub_1=a.asm.ra).apply(null,arguments)},Pb=a._emscripten_bind_btVector3_get_m_floats_1=function(){return(Pb=a._emscripten_bind_btVector3_get_m_floats_1=a.asm.sa).apply(null,arguments)},Qb=a._emscripten_bind_btVector3_set_m_floats_2=function(){return(Qb=
a._emscripten_bind_btVector3_set_m_floats_2=a.asm.ta).apply(null,arguments)},Rb=a._emscripten_bind_btVector3___destroy___0=function(){return(Rb=a._emscripten_bind_btVector3___destroy___0=a.asm.ua).apply(null,arguments)},Sb=a._emscripten_bind_btSoftBody_btSoftBody_4=function(){return(Sb=a._emscripten_bind_btSoftBody_btSoftBody_4=a.asm.va).apply(null,arguments)},Tb=a._emscripten_bind_btSoftBody_generateBendingConstraints_1=function(){return(Tb=a._emscripten_bind_btSoftBody_generateBendingConstraints_1=
a.asm.wa).apply(null,arguments)},Ub=a._emscripten_bind_btSoftBody_generateClusters_1=function(){return(Ub=a._emscripten_bind_btSoftBody_generateClusters_1=a.asm.xa).apply(null,arguments)},Vb=a._emscripten_bind_btSoftBody_generateClusters_2=function(){return(Vb=a._emscripten_bind_btSoftBody_generateClusters_2=a.asm.ya).apply(null,arguments)},Wb=a._emscripten_bind_btSoftBody_setTotalMass_1=function(){return(Wb=a._emscripten_bind_btSoftBody_setTotalMass_1=a.asm.za).apply(null,arguments)},Xb=a._emscripten_bind_btSoftBody_setTotalMass_2=
function(){return(Xb=a._emscripten_bind_btSoftBody_setTotalMass_2=a.asm.Aa).apply(null,arguments)},Yb=a._emscripten_bind_btSoftBody_setActivationState_1=function(){return(Yb=a._emscripten_bind_btSoftBody_setActivationState_1=a.asm.Ba).apply(null,arguments)},Zb=a._emscripten_bind_btSoftBody_get_m_cfg_0=function(){return(Zb=a._emscripten_bind_btSoftBody_get_m_cfg_0=a.asm.Ca).apply(null,arguments)},$b=a._emscripten_bind_btSoftBody_set_m_cfg_1=function(){return($b=a._emscripten_bind_btSoftBody_set_m_cfg_1=
a.asm.Da).apply(null,arguments)},ac=a._emscripten_bind_btSoftBody_get_m_nodes_0=function(){return(ac=a._emscripten_bind_btSoftBody_get_m_nodes_0=a.asm.Ea).apply(null,arguments)},bc=a._emscripten_bind_btSoftBody_set_m_nodes_1=function(){return(bc=a._emscripten_bind_btSoftBody_set_m_nodes_1=a.asm.Fa).apply(null,arguments)},cc=a._emscripten_bind_btSoftBody_get_m_faces_0=function(){return(cc=a._emscripten_bind_btSoftBody_get_m_faces_0=a.asm.Ga).apply(null,arguments)},dc=a._emscripten_bind_btSoftBody_set_m_faces_1=
function(){return(dc=a._emscripten_bind_btSoftBody_set_m_faces_1=a.asm.Ha).apply(null,arguments)},ec=a._emscripten_bind_btSoftBody___destroy___0=function(){return(ec=a._emscripten_bind_btSoftBody___destroy___0=a.asm.Ia).apply(null,arguments)},fc=a._emscripten_bind_btSoftRigidDynamicsWorld_btSoftRigidDynamicsWorld_5=function(){return(fc=a._emscripten_bind_btSoftRigidDynamicsWorld_btSoftRigidDynamicsWorld_5=a.asm.Ja).apply(null,arguments)},hc=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_1=
function(){return(hc=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_1=a.asm.Ka).apply(null,arguments)},ic=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_2=function(){return(ic=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_2=a.asm.La).apply(null,arguments)},jc=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_3=function(){return(jc=a._emscripten_bind_btSoftRigidDynamicsWorld_addSoftBody_3=a.asm.Ma).apply(null,arguments)},kc=a._emscripten_bind_btSoftRigidDynamicsWorld_getWorldInfo_0=
function(){return(kc=a._emscripten_bind_btSoftRigidDynamicsWorld_getWorldInfo_0=a.asm.Na).apply(null,arguments)},lc=a._emscripten_bind_btSoftRigidDynamicsWorld_removeSoftBody_1=function(){return(lc=a._emscripten_bind_btSoftRigidDynamicsWorld_removeSoftBody_1=a.asm.Oa).apply(null,arguments)},mc=a._emscripten_bind_btSoftRigidDynamicsWorld_setGravity_1=function(){return(mc=a._emscripten_bind_btSoftRigidDynamicsWorld_setGravity_1=a.asm.Pa).apply(null,arguments)},nc=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_1=
function(){return(nc=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_1=a.asm.Qa).apply(null,arguments)},oc=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_2=function(){return(oc=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_2=a.asm.Ra).apply(null,arguments)},pc=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_3=function(){return(pc=a._emscripten_bind_btSoftRigidDynamicsWorld_stepSimulation_3=a.asm.Sa).apply(null,arguments)},qc=a._emscripten_bind_btSoftRigidDynamicsWorld___destroy___0=
function(){return(qc=a._emscripten_bind_btSoftRigidDynamicsWorld___destroy___0=a.asm.Ta).apply(null,arguments)},rc=a._emscripten_bind_tFaceArray_size_0=function(){return(rc=a._emscripten_bind_tFaceArray_size_0=a.asm.Ua).apply(null,arguments)},sc=a._emscripten_bind_tFaceArray_at_1=function(){return(sc=a._emscripten_bind_tFaceArray_at_1=a.asm.Va).apply(null,arguments)},tc=a._emscripten_bind_tFaceArray___destroy___0=function(){return(tc=a._emscripten_bind_tFaceArray___destroy___0=a.asm.Wa).apply(null,
arguments)},uc=a._emscripten_bind_btSoftBodyRigidBodyCollisionConfiguration_btSoftBodyRigidBodyCollisionConfiguration_0=function(){return(uc=a._emscripten_bind_btSoftBodyRigidBodyCollisionConfiguration_btSoftBodyRigidBodyCollisionConfiguration_0=a.asm.Xa).apply(null,arguments)},vc=a._emscripten_bind_btSoftBodyRigidBodyCollisionConfiguration___destroy___0=function(){return(vc=a._emscripten_bind_btSoftBodyRigidBodyCollisionConfiguration___destroy___0=a.asm.Ya).apply(null,arguments)};
a._malloc=function(){return(a._malloc=a.asm.Za).apply(null,arguments)};a._free=function(){return(a._free=a.asm._a).apply(null,arguments)};a.dynCall_vi=function(){return(a.dynCall_vi=a.asm.$a).apply(null,arguments)};a.dynCall_v=function(){return(a.dynCall_v=a.asm.ab).apply(null,arguments)};var wc;x=function xc(){wc||yc();wc||(x=xc)};
function yc(){function b(){if(!wc&&(wc=!0,a.calledRun=!0,!ja)){oa(qa);oa(ra);aa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();sa.unshift(c)}oa(sa)}}if(!(0<w)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ta();oa(pa);0<w||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}
a.run=yc;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;yc();function z(){}z.prototype=Object.create(z.prototype);z.prototype.constructor=z;z.prototype.cb=z;z.eb={};a.WrapperObject=z;function A(b){return(b||z).eb}a.getCache=A;function B(b,c){var d=A(c),f=d[b];if(f)return f;f=Object.create((c||z).prototype);f.bb=b;return d[b]=f}a.wrapPointer=B;a.castObject=function(b,c){return B(b.bb,c)};a.NULL=B(0);
a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete A(b.cb)[b.bb]};a.compare=function(b,c){return b.bb===c.bb};a.getPointer=function(b){return b.bb};a.getClass=function(b){return b.cb};var C=0,zc=0,Bc=0,Cc=[],Dc=0;function Ec(){if(Dc){for(var b=0;b<Cc.length;b++)a._free(Cc[b]);Cc.length=0;a._free(C);C=0;zc+=Dc;Dc=0}C||(zc+=128,C=a._malloc(zc),assert(C));Bc=0}
function Fc(b,c){assert(C);b=b.length*c.BYTES_PER_ELEMENT;b=b+7&-8;Bc+b>=zc?(assert(0<b),Dc+=b,c=a._malloc(b),Cc.push(c)):(c=C+Bc,Bc+=b);return c}function Gc(b,c,d){d>>>=0;switch(c.BYTES_PER_ELEMENT){case 2:d>>>=1;break;case 4:d>>>=2;break;case 8:d>>>=3}for(var f=0;f<b.length;f++)c[d+f]=b[f]}function Hc(b){if("object"===typeof b){var c=Fc(b,ma);Gc(b,ma,c);return c}return b}function D(){throw"cannot construct a btCollisionObject, no constructor in IDL";}D.prototype=Object.create(z.prototype);
D.prototype.constructor=D;D.prototype.cb=D;D.eb={};a.btCollisionObject=D;D.prototype.setActivationState=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Ca(c,b)};D.prototype.__destroy__=function(){Da(this.bb)};function E(){throw"cannot construct a btDispatcher, no constructor in IDL";}E.prototype=Object.create(z.prototype);E.prototype.constructor=E;E.prototype.cb=E;E.eb={};a.btDispatcher=E;E.prototype.__destroy__=function(){Ea(this.bb)};
function F(){throw"cannot construct a btCollisionConfiguration, no constructor in IDL";}F.prototype=Object.create(z.prototype);F.prototype.constructor=F;F.prototype.cb=F;F.eb={};a.btCollisionConfiguration=F;F.prototype.__destroy__=function(){Fa(this.bb)};function G(){throw"cannot construct a btSoftBodySolver, no constructor in IDL";}G.prototype=Object.create(z.prototype);G.prototype.constructor=G;G.prototype.cb=G;G.eb={};a.btSoftBodySolver=G;G.prototype.__destroy__=function(){Ga(this.bb)};
function H(){throw"cannot construct a btBroadphaseInterface, no constructor in IDL";}H.prototype=Object.create(z.prototype);H.prototype.constructor=H;H.prototype.cb=H;H.eb={};a.btBroadphaseInterface=H;H.prototype.__destroy__=function(){Ha(this.bb)};function I(){throw"cannot construct a btConstraintSolver, no constructor in IDL";}I.prototype=Object.create(z.prototype);I.prototype.constructor=I;I.prototype.cb=I;I.eb={};a.btConstraintSolver=I;I.prototype.__destroy__=function(){Ia(this.bb)};
function J(){this.bb=Ja();A(J)[this.bb]=this}J.prototype=Object.create(H.prototype);J.prototype.constructor=J;J.prototype.cb=J;J.eb={};a.btDbvtBroadphase=J;J.prototype.__destroy__=function(){Ka(this.bb)};function K(){this.bb=La();A(K)[this.bb]=this}K.prototype=Object.create(G.prototype);K.prototype.constructor=K;K.prototype.cb=K;K.eb={};a.btDefaultSoftBodySolver=K;K.prototype.__destroy__=function(){Ma(this.bb)};function M(b){b&&"object"===typeof b&&(b=b.bb);this.bb=Na(b);A(M)[this.bb]=this}
M.prototype=Object.create(E.prototype);M.prototype.constructor=M;M.prototype.cb=M;M.eb={};a.btCollisionDispatcher=M;M.prototype.__destroy__=function(){Oa(this.bb)};function N(){this.bb=Pa();A(N)[this.bb]=this}N.prototype=Object.create(I.prototype);N.prototype.constructor=N;N.prototype.cb=N;N.eb={};a.btSequentialImpulseConstraintSolver=N;N.prototype.__destroy__=function(){Qa(this.bb)};function O(){throw"cannot construct a VoidPtr, no constructor in IDL";}O.prototype=Object.create(z.prototype);
O.prototype.constructor=O;O.prototype.cb=O;O.eb={};a.VoidPtr=O;O.prototype.__destroy__=function(){Ra(this.bb)};function P(){throw"cannot construct a Config, no constructor in IDL";}P.prototype=Object.create(z.prototype);P.prototype.constructor=P;P.prototype.cb=P;P.eb={};a.Config=P;P.prototype.get_timescale=P.prototype.tb=function(){return Sa(this.bb)};P.prototype.set_timescale=P.prototype.Hb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Ta(c,b)};
Object.defineProperty(P.prototype,"timescale",{get:P.prototype.tb,set:P.prototype.Hb});P.prototype.get_viterations=P.prototype.ub=function(){return Ua(this.bb)};P.prototype.set_viterations=P.prototype.Ib=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Va(c,b)};Object.defineProperty(P.prototype,"viterations",{get:P.prototype.ub,set:P.prototype.Ib});P.prototype.get_piterations=P.prototype.sb=function(){return Wa(this.bb)};
P.prototype.set_piterations=P.prototype.Gb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Xa(c,b)};Object.defineProperty(P.prototype,"piterations",{get:P.prototype.sb,set:P.prototype.Gb});P.prototype.get_collisions=P.prototype.hb=function(){return Ya(this.bb)};P.prototype.set_collisions=P.prototype.vb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Za(c,b)};Object.defineProperty(P.prototype,"collisions",{get:P.prototype.hb,set:P.prototype.vb});P.prototype.__destroy__=function(){$a(this.bb)};
function Node(){throw"cannot construct a Node, no constructor in IDL";}Node.prototype=Object.create(z.prototype);Node.prototype.constructor=Node;Node.prototype.cb=Node;Node.eb={};a.Node=Node;Node.prototype.get_m_x=Node.prototype.rb=function(){return B(ab(this.bb),Q)};Node.prototype.set_m_x=Node.prototype.Fb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);bb(c,b)};Object.defineProperty(Node.prototype,"m_x",{get:Node.prototype.rb,set:Node.prototype.Fb});
Node.prototype.get_m_f=Node.prototype.jb=function(){return B(cb(this.bb),Q)};Node.prototype.set_m_f=Node.prototype.xb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);db(c,b)};Object.defineProperty(Node.prototype,"m_f",{get:Node.prototype.jb,set:Node.prototype.xb});Node.prototype.__destroy__=function(){eb(this.bb)};function R(){throw"cannot construct a tNodeArray, no constructor in IDL";}R.prototype=Object.create(z.prototype);R.prototype.constructor=R;R.prototype.cb=R;R.eb={};
a.tNodeArray=R;R.prototype.size=R.prototype.size=function(){return fb(this.bb)};R.prototype.at=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return B(gb(c,b),Node)};R.prototype.__destroy__=function(){hb(this.bb)};function S(){throw"cannot construct a btSoftBodyArray, no constructor in IDL";}S.prototype=Object.create(z.prototype);S.prototype.constructor=S;S.prototype.cb=S;S.eb={};a.btSoftBodyArray=S;S.prototype.size=S.prototype.size=function(){return ib(this.bb)};
S.prototype.at=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return B(jb(c,b),T)};S.prototype.__destroy__=function(){kb(this.bb)};function U(){this.bb=lb();A(U)[this.bb]=this}U.prototype=Object.create(z.prototype);U.prototype.constructor=U;U.prototype.cb=U;U.eb={};a.btSoftBodyHelpers=U;
U.prototype.CreateFromTriMesh=function(b,c,d,f,m){var L=this.bb;Ec();b&&"object"===typeof b&&(b=b.bb);"object"==typeof c&&(c=Hc(c));if("object"==typeof d&&"object"===typeof d){var Ac=Fc(d,u);Gc(d,u,Ac);d=Ac}f&&"object"===typeof f&&(f=f.bb);m&&"object"===typeof m&&(m=m.bb);return B(mb(L,b,c,d,f,m),T)};U.prototype.__destroy__=function(){nb(this.bb)};function V(){this.bb=ob();A(V)[this.bb]=this}V.prototype=Object.create(z.prototype);V.prototype.constructor=V;V.prototype.cb=V;V.eb={};
a.btSoftBodyWorldInfo=V;V.prototype.get_m_gravity=V.prototype.mb=function(){return B(pb(this.bb),Q)};V.prototype.set_m_gravity=V.prototype.Ab=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);qb(c,b)};Object.defineProperty(V.prototype,"m_gravity",{get:V.prototype.mb,set:V.prototype.Ab});V.prototype.__destroy__=function(){rb(this.bb)};function W(){throw"cannot construct a Face, no constructor in IDL";}W.prototype=Object.create(z.prototype);W.prototype.constructor=W;W.prototype.cb=W;W.eb={};
a.Face=W;W.prototype.get_m_n=W.prototype.nb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return B(sb(c,b),Node)};W.prototype.set_m_n=W.prototype.Bb=function(b,c){var d=this.bb;Ec();b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);tb(d,b,c)};Object.defineProperty(W.prototype,"m_n",{get:W.prototype.nb,set:W.prototype.Bb});W.prototype.get_m_normal=W.prototype.pb=function(){return B(ub(this.bb),Q)};
W.prototype.set_m_normal=W.prototype.Db=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);vb(c,b)};Object.defineProperty(W.prototype,"m_normal",{get:W.prototype.pb,set:W.prototype.Db});W.prototype.get_m_ra=W.prototype.qb=function(){return wb(this.bb)};W.prototype.set_m_ra=W.prototype.Eb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);xb(c,b)};Object.defineProperty(W.prototype,"m_ra",{get:W.prototype.qb,set:W.prototype.Eb});W.prototype.__destroy__=function(){yb(this.bb)};
function Q(b,c,d){b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);d&&"object"===typeof d&&(d=d.bb);this.bb=void 0===b?zb():void 0===c?_emscripten_bind_btVector3_btVector3_1(b):void 0===d?_emscripten_bind_btVector3_btVector3_2(b,c):Ab(b,c,d);A(Q)[this.bb]=this}Q.prototype=Object.create(z.prototype);Q.prototype.constructor=Q;Q.prototype.cb=Q;Q.eb={};a.btVector3=Q;Q.prototype.dot=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return Bb(c,b)};
Q.prototype.length=Q.prototype.length=function(){return Cb(this.bb)};Q.prototype.length2=function(){return Db(this.bb)};Q.prototype.setX=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Eb(c,b)};Q.prototype.setY=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Fb(c,b)};Q.prototype.setZ=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Gb(c,b)};
Q.prototype.setValue=function(b,c,d){var f=this.bb;b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);d&&"object"===typeof d&&(d=d.bb);Hb(f,b,c,d)};Q.prototype.x=Q.prototype.x=function(){return Ib(this.bb)};Q.prototype.y=Q.prototype.y=function(){return Jb(this.bb)};Q.prototype.z=Q.prototype.z=function(){return Kb(this.bb)};Q.prototype.op_mul=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return B(Lb(c,b),Q)};
Q.prototype.op_div=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return B(Mb(c,b),Q)};Q.prototype.op_add=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return B(Nb(c,b),Q)};Q.prototype.op_sub=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return B(Ob(c,b),Q)};Q.prototype.get_m_floats=Q.prototype.lb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return Pb(c,b)};
Q.prototype.set_m_floats=Q.prototype.zb=function(b,c){var d=this.bb;Ec();b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);Qb(d,b,c)};Object.defineProperty(Q.prototype,"m_floats",{get:Q.prototype.lb,set:Q.prototype.zb});Q.prototype.__destroy__=function(){Rb(this.bb)};function T(b,c,d,f){Ec();b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);d&&"object"===typeof d&&(d=d.bb);"object"==typeof f&&(f=Hc(f));this.bb=Sb(b,c,d,f);A(T)[this.bb]=this}T.prototype=Object.create(D.prototype);
T.prototype.constructor=T;T.prototype.cb=T;T.eb={};a.btSoftBody=T;T.prototype.generateBendingConstraints=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return Tb(c,b)};T.prototype.generateClusters=function(b,c){var d=this.bb;b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);return void 0===c?Ub(d,b):Vb(d,b,c)};T.prototype.setTotalMass=function(b,c){var d=this.bb;b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);void 0===c?Wb(d,b):Xb(d,b,c)};
T.prototype.setActivationState=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);Yb(c,b)};T.prototype.get_m_cfg=T.prototype.ib=function(){return B(Zb(this.bb),P)};T.prototype.set_m_cfg=T.prototype.wb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);$b(c,b)};Object.defineProperty(T.prototype,"m_cfg",{get:T.prototype.ib,set:T.prototype.wb});T.prototype.get_m_nodes=T.prototype.ob=function(){return B(ac(this.bb),R)};
T.prototype.set_m_nodes=T.prototype.Cb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);bc(c,b)};Object.defineProperty(T.prototype,"m_nodes",{get:T.prototype.ob,set:T.prototype.Cb});T.prototype.get_m_faces=T.prototype.kb=function(){return B(cc(this.bb),X)};T.prototype.set_m_faces=T.prototype.yb=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);dc(c,b)};Object.defineProperty(T.prototype,"m_faces",{get:T.prototype.kb,set:T.prototype.yb});T.prototype.__destroy__=function(){ec(this.bb)};
function Y(b,c,d,f,m){b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);d&&"object"===typeof d&&(d=d.bb);f&&"object"===typeof f&&(f=f.bb);m&&"object"===typeof m&&(m=m.bb);this.bb=fc(b,c,d,f,m);A(Y)[this.bb]=this}Y.prototype=Object.create(z.prototype);Y.prototype.constructor=Y;Y.prototype.cb=Y;Y.eb={};a.btSoftRigidDynamicsWorld=Y;
Y.prototype.addSoftBody=function(b,c,d){var f=this.bb;b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);d&&"object"===typeof d&&(d=d.bb);void 0===c?hc(f,b):void 0===d?ic(f,b,c):jc(f,b,c,d)};Y.prototype.getWorldInfo=function(){return B(kc(this.bb),V)};Y.prototype.removeSoftBody=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);lc(c,b)};Y.prototype.setGravity=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);mc(c,b)};
Y.prototype.stepSimulation=function(b,c,d){var f=this.bb;b&&"object"===typeof b&&(b=b.bb);c&&"object"===typeof c&&(c=c.bb);d&&"object"===typeof d&&(d=d.bb);return void 0===c?nc(f,b):void 0===d?oc(f,b,c):pc(f,b,c,d)};Y.prototype.__destroy__=function(){qc(this.bb)};function X(){throw"cannot construct a tFaceArray, no constructor in IDL";}X.prototype=Object.create(z.prototype);X.prototype.constructor=X;X.prototype.cb=X;X.eb={};a.tFaceArray=X;X.prototype.size=X.prototype.size=function(){return rc(this.bb)};
X.prototype.at=function(b){var c=this.bb;b&&"object"===typeof b&&(b=b.bb);return B(sc(c,b),W)};X.prototype.__destroy__=function(){tc(this.bb)};function Z(){this.bb=uc();A(Z)[this.bb]=this}Z.prototype=Object.create(F.prototype);Z.prototype.constructor=Z;Z.prototype.cb=Z;Z.eb={};a.btSoftBodyRigidBodyCollisionConfiguration=Z;Z.prototype.__destroy__=function(){vc(this.bb)};this.Ammo=a;


  return Ammo.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Ammo;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Ammo; });
    else if (typeof exports === 'object')
      exports["Ammo"] = Ammo;
    